name: loremgenerator
version: 2.3.8+41
description: Lorem Ipsum Generator
contact: xrayadamo@gmail.com
icon: snap/gui/loremgenerator.png
confinement: strict
base: core24
grade: stable
license: MIT
source-code: https://github.com/XRayAdams/loremgenerator-rs
issues: https://github.com/XRayAdams/loremgenerator-rs/issues
website: https://www.rayadams.app

platforms:
  amd64:
  arm64:
    
apps:
  loremgenerator:
    command: bin/loremgenerator
    common-id: app.rayadams.loremgenerator
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11

adopt-info: loremgenerator

parts:
  loremgenerator:
    plugin: rust
    source: .
    rust-channel: stable
    parse-info: [snap/app.rayadams.loremgenerator.metainfo.xml]
    build-packages:
      - pkg-config
      - libgtk-4-dev
      - libadwaita-1-dev
      - gettext
    override-build: |
      craftctl default
      cp -r ${CRAFT_PART_SRC}/target/release/assets ${CRAFT_PART_INSTALL}/
