title: Lorem Ipsum Generator
name: loremgenerator
version: 2.3.8+40
summary: Lorem Ipsum Generator
description: Lorem Ipsum Generator
contact: xrayadamo@gmail.com
icon: snap/gui/loremgenerator.png
confinement: strict
base: core24
grade: stable
license: MIT
source-code: https://github.com/rayadams/loremgenerator-rs
website: https://www.rayadams.app

platforms:
  amd64:
  arm64:
    
apps:
  loremgenerator:
    command: bin/loremgenerator
    common-id: app.rayadams.loremgenerator
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11

parts:
  loremgenerator:
    plugin: rust
    source: .
    rust-channel: stable
    build-packages:
      - pkg-config
      - libgtk-4-dev
      - libadwaita-1-dev
